### ISSUE TITLE
default install does not play well with canonical vhost

### ISSUE THREAD

**Issue by duck-rh** [OSAS/ansible-role-httpd#12]
When website_domain is not set, the role acts on a default vhost using ansible_fqdn. This is fine in most cases, but when you use small VMs/containers where the only vhost is the canonical one, then you can have unexpected results.

In my situation, I defined the vhost first using the httpd role, it works well, then another role called later depends on the httpd role (without website_domain set). My setup includes redirects, but the dependency call on httpd role does not have any parameters, and the conditions inside the role result in redirects.conf being emptied of the previous configuration.

From what I can read in the role's code, this could happen with several other settings.

So we may say in the documentation that you HAVE to setup the canonical host _after_ all roles depending on this role. Apart from being very bothersome, this also would break divergence detection, as this would trigger many changes in the playbook run.

I wanted to add a condition on website_domain being defined for these settings, but this definitely does not seem a proper solution. Thus, no PR, discussion first.

I just remembered an Apache feature, but I don't have much knowledge of it. Maybe creating a "fallback" vhost instead of a default one using the canonical hostname would avoid changing too much the current working system. A conf.d/default.conf containing "`<VirtualHost __default__:80>`" and just a simple fallback config could be setup if website_domain is not set, and the rest of the role would only be run if it is set (also easier to visualize both path).

The old config could stay, I think it is harmless. I don't how to cleanup without messing with user-defined canonical vhosts.

**Comment by duck-rh** [comment]
As for _default_, IIUC it was not meant to be used with named-based virtualhosts. Now in Apache 2.4 it is an alias for "*", so this is not a good idea (and explains my problem in #15).

Never the less with the order made in #15 we could have a default config using a higher prefix I guess. It seems first declaration wins and there is nothing mixed-overriden.

**Comment by mscherer** [comment]
So the problem ultimately is likely the naming of the role, because the current name do not convey that the role manage vhost more than httpd. And because the role is supposed and made to manage 1 vhost per service, it do make a lot of assumption that do indeed break when you do not do it.

For a start, since the idea is to be declarative, each vhost should be managed in 1 and 1 single place. We can't be managing addition and removal of configuration if there is no central external state (or source of truth) and more than 1 role invocation to modify things. 

If we want to let the role add and remove redirects (as a example), we have 3 possibility:
First, we can say "here is the complete list of redirect", and the role make sure thats the list is here, and nothing else (in the file) is present.
Second, we can say "here is the list to add, here is the list to remove, and do not touch to anything who is not there". 
Or the 3rd way of "here is the list of things that need to be present, do not remove anything".

The 2nd do accommodate external modification, like someone touching to the file adding a redirect not in the 2 lists. However, this is neither what we want (ie, let something messing with the role responsibility), and that also mean removal are more complicated, with potentially the burden of a ever growing list of redirect to remove.

And if we use the 3rd method, this mean there is lots of left over on a traditional server. It would work fine for a image based deployment (ie, either container, and/or VM image) were everything is done from scratch on eac change, but we are not there yet, far from it.

So as we wanted to be able to clean leftover configuration, we have to use the 1st method. And this one do not accommodate calling the role twice on the same vhost with different parameters, because this assume that each vhost is managed only once.

So no, I do not think the current architecture can be changed to supported the use case of "multiple services on the same vhost" without adding complexity and/or removing features (ie, cleaning) that would bite us later.

The best that can be done is to use the vhost declaration, but instead of using the redirects/etc management of the role, to do it directly in the calling role.

For example, for a nagios role, instead of having:
```
{ role: httpd, redirect: "/", "/nagios"}
```

Just include httpd, as a minimal httpd setup, and manage redirects manually in the nagios role by adding file.
 
The role was not really made for a shared vhost setup as you have, and make lots of assumptions that do break when you do that. And I am not sure I would recommend trying to do that.

**Comment by duck-rh** [comment]
Let's clarify. I never used this role in anyway except fully (website_domain + other params) or naked (no parameters at all, for dependency reasons). So when I say "When website_domain is not set", in fact I set nothing else.

This said, I use the role as dependency in the 'rt' role, without any parameter, and then I define the vhost with parameters only once in the playbook. Now that it is pushed you can have a look at it in the Cage repository, but this is very basic construct:
```
  - role: httpd
    website_domain: "{{ ansible_fqdn }}"
    redirects:
    - src: '^/$'
      target: '/rt'
      match: True
    use_letsencrypt: True
    force_tls: True
```
The only specific here is using ansible_fqdn as website_domain. In the past the machine had a name and the vhost another, so we never experienced this.

This said, I agree with what you do and I don't think it is reasonable to create a complete state machine for out need, but here I'm setting up the vhost only once and this is a bug.
